name: Spec Conformance
description: File an issue to track conformance of a certain block to the spec.
title: 'spec: ...'
labels: [spec conformance, needs triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description:
        Please search to see if an issue already exists for the bug you
        encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Which component is not built according to the spec?
      options:
        - Generator
        - Registry
        - Renderer
        - Template Store
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what the current behaviour is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Spec Defined Behavior
      description: A concise description of what the spec defines should happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 18.4.0
          - **Docker**: 20.10.17
      value: |
        - OS:
        - Node:
        - Docker:
      render: markdown
    validations:
      required: false
